name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.5.2
  - seaborn=0.11.1
  - pandas=1.2.3
  - pip=22.1.2
  - pandas-profiling=2.11.0
  - pyarrow=2.0
  - pip:
      - wandb==0.13.2
      - protobuf==3.20.*