name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.2.3
  - pip=22.1.2
  - mlflow=1.28.0
  - scikit-learn=0.24.1
  - matplotlib=3.5.3
  - pillow=9.2.0
  - pip:
      - wandb==0.13.2
      - protobuf==3.20.*
